db_metrics_tbl <- read_csv("data/db_metrics.csv") %>%
  filter(
    .data$db_metric_name != "Donors - HCRP (OPO/Hospital motivated)",
    .data$db_metric_name != "EDC Productivity",
    .data$metric_type_id <= 7,
    .data$metric_type_id != 6
  ) %>%
  select(.data$metric_id, .data$db_metric_name)

file_metrics_18 <- c(
  "Total deaths in hospitals served",
  "Total deaths in units served during working hours",
  "Total death notifications to the eye bank",
  "Potential donors screened by EB staff with doctor, nurse, or medical chart",
  "Potential Donors initially suitable for transplant",
  "Approached potential donors",
  "Consented potential donors - HCRP",
  "Donors - HCRP",
  "Donors - Voluntary",
  "Donors - Eye Retrieval Centers",
  "Donors - Other Sources",
  "Eyes or corneas - HCRP motivated",
  "Eyes or corneas - Voluntary",
  "Eyes or corneas - Eye Retrieval Centers",
  "Eyes or corneas - Other Sources",
  "Total eyes or corneas recovered with intent for transplant",
  "Total Eyes/corneas recovered with intent for research, training, and other uses - All sources",
  "Donor eligibility (medical history, serology, etc.)",
  "Tissue Suitability (specular/slit-lamp)",
  "Other issues",
  "Optical grade (PK, EK, ALK)",
  "suitable - Therapeutic, tectonic, KLAL, or K-pro only",
  "Tissue Expired",
  "Optical (PK, EK, ALK)",
  "distributed - Therapeutic, tectonic, KLAL, or K-pro only",
  "Total tissues distributed and used for keratoplasty",
  "HCRP donor tissue used",
  "Voluntary donor tissue used",
  "Eye Retrieval Center donor tissue used",
  "Other sourced donor tissue used",
  "Tissues distributed for keratoplasty but not used",
  "Tissues distributed for non-surgical use",
  "EDC Productivity (No of HCRP Transplants/No. of Active EDCs)",
  "Transplants that were recovered as MLC cases"
)

file_metrics_19 <- c(
  "Total deaths in hospitals served",
  "Total deaths in units served during working hours",
  "Total death notifications to the eye bank",
  "Potential donors screened by EB staff with doctor, nurse, or medical chart",
  "Potential Donors initially suitable for transplant",
  "Approached potential donors",
  "Consented potential donors - HCRP",
  "Donors - HCRP",
  "Donors - Voluntary",
  "Donors - Eye Retrieval Centers",
  "Donors - Other Sources",
  "Eyes or corneas - HCRP motivated",
  "Eyes or corneas - Voluntary",
  "Eyes or corneas - Eye Retrieval Centers",
  "Eyes or corneas - Other Sources",
  "Total eyes or corneas recovered with intent for transplant",
  "Total Eyes/corneas recovered with intent for research, training, and other uses - All sources",
  "Donor eligibility (medical history, serology, etc.)",
  "Tissue Suitability (specular/slit-lamp)",
  "Other issues",
  "Optical grade (PK, EK, ALK)",
  "suitable - Therapeutic, tectonic, KLAL, or K-pro only",
  "Tissue Expired",
  "Optical (PK, EK, ALK)",
  "distributed - Therapeutic, tectonic, KLAL, or K-pro only",
  "Total tissues distributed and used for keratoplasty",
  "HCRP donor tissue used",
  "Voluntary donor tissue used",
  "Eye Retrieval Center donor tissue used",
  "Other sourced donor tissue used",
  "Tissues distributed for keratoplasty but not used",
  "Tissues distributed for non-surgical use",
  "Number of Active EDCs",
  "Transplants that were recovered as MLC cases",
  "HCRP Tissue Utilization Rate",
  "Death Notification Rate (in units served during working hours)",
  "Suitability Rate %",
  "Consent Rate %",
  "Overall Transplant Rate or Utilization Rate (Total Transplanted / Total Recovered):"
)

metrics_tbl <- db_metrics_tbl %>%
  mutate(file_metric_names = file_metrics_19)

